<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'b6cf4be225367f983fe18eac5dec0fa6769ffe6b',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'b6cf4be225367f983fe18eac5dec0fa6769ffe6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'anovsiradj/cutter' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'e19af0f20544552ce790d75d12eb9f66ccc26f98',
            'type' => 'library',
            'install_path' => __DIR__ . '/../anovsiradj/cutter',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'npm-asset/apexcharts' => array(
            'pretty_version' => '5.3.5',
            'version' => '5.3.5.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/apexcharts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/bootstrap' => array(
            'pretty_version' => '5.3.3',
            'version' => '5.3.3.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/bootstrap-icons' => array(
            'pretty_version' => '1.13.1',
            'version' => '1.13.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/bootstrap-icons',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/codemirror' => array(
            'pretty_version' => '6.65.7',
            'version' => '6.65.7.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/codemirror',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/datatables.net' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/datatables.net',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/datatables.net-bs5' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/datatables.net-bs5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/esri-leaflet' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/esri-leaflet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/esri-leaflet-geocoder' => array(
            'pretty_version' => '3.1.5',
            'version' => '3.1.5.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/esri-leaflet-geocoder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fontsource--inter' => array(
            'pretty_version' => '5.2.8',
            'version' => '5.2.8.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fontsource--inter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fslightbox' => array(
            'pretty_version' => '3.5.1',
            'version' => '3.5.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fslightbox',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fullcalendar' => array(
            'pretty_version' => '6.1.18',
            'version' => '6.1.18.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fullcalendar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fullcalendar--core' => array(
            'pretty_version' => '6.1.19',
            'version' => '6.1.19.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fullcalendar--core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fullcalendar--daygrid' => array(
            'pretty_version' => '6.1.19',
            'version' => '6.1.19.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fullcalendar--daygrid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fullcalendar--interaction' => array(
            'pretty_version' => '6.1.18',
            'version' => '6.1.18.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fullcalendar--interaction',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fullcalendar--list' => array(
            'pretty_version' => '6.1.19',
            'version' => '6.1.19.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fullcalendar--list',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fullcalendar--multimonth' => array(
            'pretty_version' => '6.1.19',
            'version' => '6.1.19.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fullcalendar--multimonth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/fullcalendar--timegrid' => array(
            'pretty_version' => '6.1.18',
            'version' => '6.1.18.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/fullcalendar--timegrid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/inter-ui' => array(
            'pretty_version' => '4.1.1',
            'version' => '4.1.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/inter-ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/jquery' => array(
            'pretty_version' => '3.7.1',
            'version' => '3.7.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/jsvectormap' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/jsvectormap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/leaflet' => array(
            'pretty_version' => '1.9.4',
            'version' => '1.9.4.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/leaflet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/leaflet.markercluster' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/leaflet.markercluster',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/litepicker' => array(
            'pretty_version' => '2.0.12',
            'version' => '2.0.12.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/litepicker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/nouislider' => array(
            'pretty_version' => '15.8.1',
            'version' => '15.8.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/nouislider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/orchidjs--sifter' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/orchidjs--sifter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/orchidjs--unicode-variants' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/orchidjs--unicode-variants',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/popperjs--core' => array(
            'pretty_version' => '2.11.8',
            'version' => '2.11.8.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/popperjs--core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/preact' => array(
            'pretty_version' => '10.12.1',
            'version' => '10.12.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/preact',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/svgdotjs--svg.draggable.js' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/svgdotjs--svg.draggable.js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/svgdotjs--svg.filter.js' => array(
            'pretty_version' => '3.0.8',
            'version' => '3.0.8.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/svgdotjs--svg.filter.js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/svgdotjs--svg.js' => array(
            'pretty_version' => '3.2.4',
            'version' => '3.2.4.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/svgdotjs--svg.js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/svgdotjs--svg.resize.js' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/svgdotjs--svg.resize.js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/svgdotjs--svg.select.js' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/svgdotjs--svg.select.js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/sweetalert2' => array(
            'pretty_version' => '11.19.1',
            'version' => '11.19.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/sweetalert2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/swiper' => array(
            'pretty_version' => '12.0.3',
            'version' => '12.0.3.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/swiper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/tabler--core' => array(
            'pretty_version' => '1.0.0-beta24',
            'version' => '1.0.0.0-beta24',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/tabler--core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/tabler--icons' => array(
            'pretty_version' => '3.35.0',
            'version' => '3.35.0.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/tabler--icons',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/terraformer--arcgis' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/terraformer--arcgis',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/terraformer--common' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'reference' => '69dd81e25bdfda536b697660e4df054b1e8ba663',
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/terraformer--common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/tiny-binary-search' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/tiny-binary-search',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/tom-select' => array(
            'pretty_version' => '2.4.3',
            'version' => '2.4.3.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/tom-select',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/yr--monotone-cubic-spline' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => null,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/yr--monotone-cubic-spline',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '63afe740e99a13ba87ec199bb07bbdee937a5b62',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '6d857f4d76bd4b343eac26d6b539585d2bc56493',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => '476c4ae17f43a9a36650c69879dcf5b1e6ae724d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
